name: tea_coffee_app
description: An app to neatly take orders of all customers and show if ready or not.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.3
  provider: ^6.0.3
  flutter_spinkit: ^5.1.0
  firebase_core: ^2.24.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
